### ISSUE TITLE
[データ加工] nb009を.spacy形式に変換する

### ISSUE THREAD

**Issue by riow1983** [riow1983/Kaggle-Coleridge-Initiative#14]
オリジナル実装:
https://github.com/Toru-Ito1/Kaggle-Coleridge/blob/master/spacy-train-data-rf.ipynb

参考ブログ:
https://medium.com/analytics-vidhya/custom-named-entity-recognition-ner-model-with-spacy-3-in-four-steps-7e903688d51

spaCy trainに必要なconfigファイルの作成方法:
https://spacy.io/usage/training#config

**Comment by Toru-Ito1** [comment]
trainとinferenceを実行するコードを上げました。宜しくお願いします。
https://github.com/Toru-Ito1/Kaggle-Coleridge/blob/master/spacy-train.ipynb
https://github.com/Toru-Ito1/Kaggle-Coleridge/blob/master/ex-data-patern-spacy3-tr-0-604.ipynb

**Comment by riow1983** [comment]
@Toru-Ito1 ありがとうございます。
実行していく中でまた改めて質問するかと思いますが、その際はよろしくお願いします。

**Comment by riow1983** [comment]
@Toru-Ito1 さん、早速すみません、spacy-train.ipynbの`!python -m spacy init fill-config ../input/spacy-train-set/base_config2.cfg config.cfg`でこけました。

https://www.kaggle.com/ti110106/spacy-train-set
を作成したnotebookも共有いただけないでしょうか？
（configファイルの作成方法を確認させていただきたく。）

**Comment by riow1983** [comment]
https://spacy.io/usage/training#config
からbase_config.cfgはコピペしてきたということですかね？
base_config2.cfgをそのまま流用してみたいと思います。

**Comment by riow1983** [comment]
@Toru-Ito1 追加で２点質問していいですか？
(1) `!python -m spacy train config.cfg --output ./output/cv0-DA  --paths.train ../input/spacy-train-set/cv_train_0_DA.spacy --paths.train ../input/spacy-train-set/cv_train_0.spacy  --paths.dev ../input/spacy-train-set/cv_valid_0.spacy   --gpu-id 0 `
これには--paths.trainが二つ入っているように見えるのですが、どういう意図があるのでしょうか？

(2) 上記コマンドの--paths.trianは一つだけにして実行してみたところ`ImportError: PyTorch support requires torch: pip install thinc[torch]`というエラーに遭遇しました。伊藤さんは遭遇しませんでしたか？

**Comment by Toru-Ito1** [comment]
データのパスを指定するためには都度--paths.train を使用する必要があります。このバージョンでは二つのspacyファイルを使用していたため二回入っています。

**Comment by riow1983** [comment]
`ImportError: PyTorch support requires torch: pip install thinc[torch]`は
thinc/util.pyの"assert pytorch installed"が原因のようだ, pytorchはインストールされている. 
https://github.com/explosion/thinc/blob/master/thinc/util.py

**Comment by riow1983** [comment]
@Toru-Ito1 さん、すみませんまた教えてください。trainは無事完了し、inferenceを行おうとしております。
それでinference notebookを実行したところエラーというか`pred_ner`に何も入っていない現象に遭遇しました。以下の保存済みノートブックも同じ状態ですね。
![input file image](https://github.com/riow1983/Kaggle-Coleridge-Initiative/blob/main/png/20210714.png?raw=true)

簡単な解決方法がありましたでしょうか？
なお見ているnotebookは[こちら](https://www.kaggle.com/ti110106/ex-data-patern-spacy3-tr-0-604?scriptVersionId=66122583)のver.2です。

**Comment by riow1983** [comment]
> (2) 上記コマンドの--paths.trianは一つだけにして実行してみたところ`ImportError: PyTorch support requires torch: pip install thinc[torch]`というエラーに遭遇しました。伊藤さんは遭遇しませんでしたか？

上記エラーは`!pip install thinc==8.0.7`で解消した.

**Comment by riow1983** [comment]
> inference notebookを実行したところエラーというかpred_nerに何も入っていない現象に遭遇しました。以下の保存済みノートブックも同じ状態ですね。

これはsample submissionに対してpred_nerが空になっていただけの話で、そのままsubmitしてOK.

**Comment by riow1983** [comment]
> 問題点: 最後のcv_valid_{​k}​.spacyを作成する際、fold 3, 4分については作成できず。l1の長さが0になってしまっているのが原因と思われ。
作成ノートブック: https://github.com/riow1983/Kaggle-Coleridge-Initiative/blob/main/notebooks/localnb003-spacy-dataset.ipynb

上記"fold3, 4分"とはそれぞれ+1してfold4,5のことを表している.
作成できた.scapyファイルは以下の通り:
```
fold1, cv_train_0.spacy, cv_valid_0.spacy
fold2, cv_train_1.spacy, cv_valid_1.spacy
fold3, cv_train_2.spacy, cv_valid_2.spacy
fold4, cv_train_3.spacy, 作成できず
fold5, cv_train_4.spacy, 作成できず
```
localnb004でfold3を使ったspacyモデルを作成し, late submitしたがprivate LB / public LB = 0.317 / 0.566だった.
続いてfold1, 2のspacyモデルも作成し, fod3とアンサンブルしてlate submitしてみる.

**Comment by riow1983** [comment]
やりたいことは試せたのでクローズする.
